const rock = document.querySelector('.rock')
const paper = document.querySelector('.paper')
const scissors = document.querySelector('.scissors')
const winner = document.querySelector('.winner')
const playerScore = document.querySelector('.playerScore')
const computerScore = document.querySelector('.computerScore')
const returnResult = document.querySelector('.returnResult')
